fundmanager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('manager.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                          document_root=settings.MEDIA_ROOT)

manager/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from pprint import pprint
from rest_framework_nested import routers
from django.urls import path, include
from . import views
from . views import *


router = routers.DefaultRouter()
router.register('funds-list', views.FundViewSet, basename='funds-list')
router.register('investors-list', views.InvestorViewSet, basename='investors-list')
router.register('fund-close', views.FundCloseViewSet, basename='fund-close')
router.register('investor-types', views.InvestorTypesViewSet, basename='investor-types')
router.register('fund-structures', views.FundStructuresViewSet, basename='fund-strtuctures')
router.register('investor-contacts', views.ContactListViewSet, basename='investor-contacts')
router.register('investor-documents', views.InvestorDocumentsViewSet, basename='investor-documents')
router.register('committed-capital', views.CommittedCapitalViewSet, basename='committed-capital')
router.register('call-type', views.CallTypeViewSet, basename='call-type')
router.register('distribution-type', views.DistributionTypeViewSet, basename='distribution-type')
router.register('expense-category', views.ExpenseCategoryViewSet, basename='expense-category')
router.register('expense-type', views.ExpenseTypeViewSet, basename='expense-type')
router.register('capital-call', views.CapitalCallViewSet, basename='capital-call')
router.register('distribution', views.DistributionViewSet, basename='distribution')
router.register('company', views.CompanyViewSet, basename='company')
router.register('investment', views.InvestmentViewSet, basename='investment')
router.register('disbursement', views.DisbursementViewSet, basename='disbursement')
router.register('countries', views.CountryViewSet, basename='countries')
router.register('currencies', views.CurrencyViewSet, basename='currencies')
router.register('industry', views.IndustryViewSet, basename='industry')
router.register('instrument', views.InstrumentViewSet, basename='instrument')
router.register('net-asset-value', views.NetAssetValueViewSet, basename='net-asset-value')
router.register('investor-contact', views.InvesotContactViewSet, basename='investor-contact')
router.register('allocation-rule', views.AllocationRuleViewSet, basename='allocation-rule')
router.register('fund-parameters', views.FundParameterViewSet, basename='fund-parameters')

#investors_router = routers.NestedDefaultRouter(router, 'investors', lookup='investors_pk')
#investors_router.register('contacts',views.ContactViewSet, basename='investor-contacts')

urlpatterns = [
    path('api/',include(router.urls)),
#    path('', HomePageView.as_view(), name='home'),
    path('__debug__/', include(debug_toolbar.urls)),

    # Authentication
    path('register/', CustomRegisterView.as_view(), name='register'),
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    # Funds
    path('funds/', FundsList.as_view(), name='funds'),
    path('funds/<int:pk>', FundDetail.as_view(), name='fund_detail'),
    path('add_fund/', AddFund.as_view(), name='add_fund'),
    path('edit_fund/<int:pk>/', EditFund.as_view(), name='edit_fund'),
    path('delete_fund/<int:pk>/', DeleteFund.as_view(), name='delete_fund'),
    # Fund Operations
    path('funds/<int:pk>/commit/', FundCloseView.as_view(), name='fund_close'),
    path('funds/<int:fund_pk>/investor/<int:investor_pk>/commitments/', InvestorCommitmentsView.as_view(), name='investor_commitments'),
    path('fund/<int:pk>/capital_call/', CapitalCallView.as_view(), name='capital_call'),
    # Fund Parameter Management
    path('fund-parameters/', FundParameterListView.as_view(), name='fund_parameter_list'),
    path('fund-parameters/new/', FundParameterCreateView.as_view(), name='fund_parameter_create'),
    path('fund-parameters/<int:pk>/edit/', FundParameterUpdateView.as_view(), name='fund_parameter_edit'),
    # Management Fee Calculation
    path('calculate-management-fees/', CalculateManagementFeesView.as_view(), name='calculate_management_fees'),
    path('management-fees/', ManagementFeeListView.as_view(), name='management_fee_list'),
    path('management-fees/<int:fee_id>/mark-paid/', mark_fee_paid, name='mark_fee_paid'),
    path('management-fees/<int:fee_id>/delete/', delete_management_fee, name='delete_management_fee'),
    # Investors
    path('investors/', InvestorsList.as_view(), name='investors'),
    path('investors/<int:pk>', InvestorDetail.as_view(), name='investor_detail'),
    path('add_investor/', AddInvestor.as_view(), name='add_investor'),
    path('edit_investor/<int:pk>/', EditInvestor.as_view(), name='edit_investor'),
    path('delete_investor/<int:pk>/', DeleteInvestor.as_view(), name='delete_investor'),
    # Investments
    #path('investments/', InvesmentsList.as_view(),name='investments'),
    path('investments/', InvestmentsDashboard.as_view(), name='investments'),
    path('investments/<int:pk>', InvestmentDetail.as_view(),name='investment_detail'),
    path('add_investment/', AddInvestment.as_view(), name='add_investment'),
    path('edit_investment/<int:pk>/', EditInvestment.as_view(), name='edit_investment'),
    path('delete_investment/<int:pk>/', DeleteInvestment.as_view(), name='delete_investment'),
    #Companies
    path('companies/', CompaniesList.as_view(), name='companies'),
    path('companies/<int:pk>', CompanyDetail.as_view(),name='company_detail'),
    path('add_company/', AddCompany.as_view(), name='add_company'),
    path('edit_company/<int:pk>/', EditCompany.as_view(), name='edit_company'),
    path('delete_company/<int:pk>/', DeleteCompany.as_view(), name='delete_company'),
    # Contacts
    path('contacts/', ContactsList.as_view(), name='contacts'),
    path('contacts/<int:pk>', ContactDetail.as_view(),name='contact_detail'),
    path('add_contact/', AddContact.as_view(), name='add_contact'),
    path('edit_contact/<int:pk>/', EditContact.as_view(), name='edit_contact'),
    path('delete_contact/<int:pk>/', DeleteContact.as_view(), name='delete_contact'),

    path('contacts/<int:pk>/links/add/', InvestorContactCreateView.as_view(), name='contact_link_add'),
    path('contacts/<int:pk>/links/<int:link_pk>/edit/', InvestorContactUpdateView.as_view(), name='contact_link_edit'),
    path('contacts/<int:pk>/links/<int:link_pk>/delete/', InvestorContactDeleteView.as_view(), name='contact_link_delete'),

    #Reports
    path('dashboard/', Dashboard.as_view(), name='dashboard'),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#pprint(urlpatterns)

manager/models.py
from decimal import Decimal
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.shortcuts import reverse
from .choices import FeeFrequency, FeeBasis, Month
from django.db.models import Q

class InvestorType(models.Model):
    category = models.CharField(max_length=100)

    def __str__(self):
        return str(self.category)

class Country(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Countries'

    def __str__(self):
        return str(self.name)

class Investor(models.Model):
    name = models.CharField(max_length=255)
    short_name = models.CharField(max_length=10)
    logo = models.ImageField(upload_to='investors',default='no_picture.png', null=True)
    reg_no = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=20)
    country = models.ForeignKey(Country,on_delete=models.PROTECT)
    post_code = models.CharField(max_length=10)
    category = models.ForeignKey(InvestorType, on_delete=models.DO_NOTHING)

    def __str__(self):
        return str(self.name)
    
    def get_absolute_url(self):
        return reverse('investor_detail', kwargs={'pk':self.pk})

class Contact(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    id_number = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20)
    email_address = models.EmailField(max_length=100)

    def __str__(self):
        return str(self.name) + ' ' + str(self.surname)

    def get_absolute_url(self):
        return reverse('contact_detail', kwargs={'pk':self.pk})

class InvestorContact(models.Model):
    contact = models.ForeignKey(Contact,on_delete=models.CASCADE,null=False)
    investor = models.ForeignKey(Investor,on_delete=models.CASCADE,null=False)
    primary_contact = models.BooleanField(default=False)
    adv_board_rep = models.BooleanField(default=False)
    invest_comm_rep = models.BooleanField(default=False)
    reports = models.BooleanField(default=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['contact', 'investor'], name='uniq_contact_investor'),
            models.UniqueConstraint(
                fields=['investor'],
                condition=Q(primary_contact=True),
                name='uniq_primary_contact_per_investor'
            )
        ]

    def save(self, *args, **kwargs):
        # Automatically unset any other primary for this investor
        if self.primary_contact:
            InvestorContact.objects.filter(
                investor=self.investor,
                primary_contact=True
            ).exclude(pk=self.pk).update(primary_contact=False)
        super().save(*args, **kwargs)

class InvestorDocument(models.Model):
    investor = models.ForeignKey(Investor,on_delete=models.CASCADE,null=False)
    description = models.CharField(max_length=255,null=False)
    document = models.FileField(upload_to='investors',null=True)

class Currency(models.Model):
    name = models.CharField(max_length=50)   
    code = models.CharField(max_length=4)
    symbol = models.CharField(max_length=1, null=False)

    def __str__(self):
        return f"{self.symbol} ({self.code})"

    class Meta:
        verbose_name_plural = 'Currencies'

class FundStructure(models.Model):
    structure = models.CharField(max_length=100)

    def __str__(self):
        return str(self.structure)

class Fund(models.Model):
    name = models.CharField(max_length=200)
    short_name = models.CharField(max_length=20)
    objective = models.TextField(max_length=300, blank=True)
    investment_period = models.IntegerField(default=0,)
    divestment_period = models.IntegerField(default=0)
    life = models.IntegerField(default=0)
    target_commitment = models.DecimalField(max_digits=12,decimal_places=2,default=0.00)
    man_fee = models.DecimalField(max_digits=4, default=0.00,decimal_places=3)
    structure = models.ForeignKey(FundStructure,on_delete=models.PROTECT)
    currency = models.ForeignKey(Currency,on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.name)
    
    def save(self, *args, **kwargs):
        self.life = self.investment_period + self.divestment_period
        super().save(*args, **kwargs)

    def currency_symbol(self):
        return self.currency.symbol    
    
    def get_absolute_url(self):
        return reverse('fund_detail', kwargs={'pk':self.pk})

    def get_first_commitment_date(self):
        """Return the date of the first committed capital for this fund"""
        first_commitment = CommittedCapital.objects.filter(
            fund=self
        ).order_by('date').first()
        
        if first_commitment:
            return first_commitment.date
        return None

class FundParameter(models.Model):
    fund = models.OneToOneField(Fund, on_delete=models.CASCADE, related_name='parameters')
    
    # VAT Configuration
    vat_registered = models.BooleanField(
        default=False,
        help_text="Whether the fund manager is VAT registered"
    )
    vat_rate = models.DecimalField(
        max_digits=5, 
        decimal_places=3,
        default=Decimal('0.15'),  # 15% default VAT rate
        help_text="VAT rate to apply (e.g., 0.15 for 15%)"
    )

    # Fee Calculation Configuration
    fee_frequency = models.CharField(
        max_length=1,
        choices=FeeFrequency.choices,
        default=FeeFrequency.QUARTERLY
    )
    investment_period_fee_basis = models.CharField(
        max_length=1,
        choices=FeeBasis.choices,
        default=FeeBasis.COMMITTED_CAPITAL
    )
    divest_period_fee_basis = models.CharField(
        max_length=1,
        choices=FeeBasis.choices,
        default=FeeBasis.INVESTED_CAPITAL
    )
    
    # Fiscal Year Configuration
    fiscal_year_end_month = models.CharField(
        max_length=3,
        choices=Month.choices,
        default=Month.DECEMBER
    )
    
    # Flexible Period End Configuration
    period1_end_month = models.CharField(max_length=3, choices=Month.choices, blank=True, null=True)
    period2_end_month = models.CharField(max_length=3, choices=Month.choices, blank=True, null=True)
    period3_end_month = models.CharField(max_length=3, choices=Month.choices, blank=True, null=True)
    period4_end_month = models.CharField(max_length=3, choices=Month.choices, blank=True, null=True)
    period5_end_month = models.CharField(max_length=3, choices=Month.choices, blank=True, null=True)
    period6_end_month = models.CharField(max_length=3, choices=Month.choices, blank=True, null=True)
    period7_end_month = models.CharField(max_length=3, choices=Month.choices, blank=True, null=True)
    period8_end_month = models.CharField(max_length=3, choices=Month.choices, blank=True, null=True)
    period9_end_month = models.CharField(max_length=3, choices=Month.choices, blank=True, null=True)
    period10_end_month = models.CharField(max_length=3, choices=Month.choices, blank=True, null=True)
    period11_end_month = models.CharField(max_length=3, choices=Month.choices, blank=True, null=True)
    period12_end_month = models.CharField(max_length=3, choices=Month.choices, blank=True, null=True)
    
    investment_period_end_date = models.DateField()
    
    class Meta:
        verbose_name = "Fund Parameter"
        verbose_name_plural = "Fund Parameters"

    def get_period_end_months(self):
        """Return list of period end months based on frequency and configuration"""
        # Get all non-empty custom period end months
        custom_months = []
        for i in range(1, 13):
            field_name = f'period{i}_end_month'
            month_value = getattr(self, field_name)
            if month_value:
                custom_months.append(month_value)
        
        # If custom months are defined, use them
        if custom_months:
            return custom_months
        
        # Default behavior based on frequency
        if self.fee_frequency == FeeFrequency.ANNUALLY:
            return [self.fiscal_year_end_month]
        
        elif self.fee_frequency == FeeFrequency.SEMI_ANNUALLY:
            # Default: 6 months apart
            month_num = Month.values.index(self.fiscal_year_end_month) + 1
            mid_year_num = (month_num - 6) % 12 or 12
            mid_year_month = Month.values[mid_year_num - 1]
            return [mid_year_month, self.fiscal_year_end_month]
        
        elif self.fee_frequency == FeeFrequency.QUARTERLY:
            # Default: standard quarters
            month_num = Month.values.index(self.fiscal_year_end_month) + 1
            q1_num = (month_num - 9) % 12 or 12
            q2_num = (month_num - 6) % 12 or 12
            q3_num = (month_num - 3) % 12 or 12
            return [
                Month.values[q1_num - 1],
                Month.values[q2_num - 1], 
                Month.values[q3_num - 1],
                self.fiscal_year_end_month
            ]
        
        elif self.fee_frequency == FeeFrequency.MONTHLY:
            return list(Month.values)
        
        return []

class FundClose(models.Model):
    fund = models.ForeignKey(Fund,on_delete=models.CASCADE)
    close_date = models.DateField(auto_now=False)
    series_number = models.SmallIntegerField(null=False, default=0)
    final_close = models.BooleanField(default=False)

    def __str__(self):
        return str(self.fund) + ' | ' + str(self.series_number)
    
class CallType(models.Model):
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=20, choices=(
        ('INVESTMENT', 'Investment'),
        ('EXPENSE', 'Expense'),
        ('FEE', 'Fee')
    ), default='EXPENSE')

    def __str__(self):
        return str(self.name)

class ExpenseCategory(models.Model):

manager/templates/funds/confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block title %}
    Delete Fund
{% endblock title %}

{% block content %}
<div class="container col-md-10 offset-md-1 mt-3">
    <h2 class="">Delete Fund</h2>
    <hr class="">
    <form action="" method="post" autocomplete="off">
        {% csrf_token %}
        <p class="">Are you sure you want to delete "{{ object }}"?</p>
        <div class="col-md-6 mt-3">
            <input type="submit" value="confirm" class="btn btn-block btn-success btn-sm col-md-3">
            <a href="{% url 'funds' %}" class="btn btn-secondary btn-sm btn-block btn-danger col-md-3"><i class="fas fa-danger"></i> Return</a>
        </div>
    </form>
</div>

{% endblock content %}

manager/templates/funds/edit_fund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block title %}
    Edit Fund
{% endblock title %}

{% block content %}
<div class="container col-md-10 offset-md-1 mt-3">
    <h2 class="">Edit Fund</h2>
    <hr class="">
    <form action="" method="post" autocomplete="off">
        {% csrf_token %}
        {{ form | crispy }}
        
        <div class="col-md-6 mt-3">
            <button type="submit" value="submit" class="btn btn-block btn-success btn-sm col-md-3"><i class="fas fa-save"></i>  Save</button>
            <a href="{% url 'funds' %}" class="btn btn-secondary btn-sm btn-block btn-danger col-md-3"><i class="fas fa-danger"></i> Close</a> 
        </div>    
    </form>
</div>

{% endblock content %}

manager/templates/funds/fund_parameter_form.html
<!-- templates/funds/fund_parameter_form.html -->
{% extends "base.html" %}
{% load static crispy_forms_tags %}
{% load custom_filters %}
{% load humanize %}

{% block content %}
<div class="container-fluid">
    <div class="row mb-4">
        <div class="col">
            <h2>
                <i class="fas fa-cog me-2"></i>
                {% if is_create %}Create{% else %}Edit{% endif %} Fund Parameters: {% if not is_create %}{{ object.fund.name }}{% endif %}
            </h2>
            <p class="text-muted">Configure how management fees are calculated for this fund</p>
        </div>
    </div>

    <!-- DEBUG: Show all available fields -->
    <div class="row mb-3" style="display: none;">
        <div class="col">
            <h6>Available Form Fields:</h6>
            <ul>
                {% for field in form %}
                    <li>{{ field.name }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title mb-0">Fee Calculation Settings</h5>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        
                        {% if is_create %}
                        <div class="row">
                            <div class="col-md-12">
                                {{ form.fund|as_crispy_field }}
                            </div>
                        </div>
                        {% endif %}

                        <!-- Test each field individually to find the problematic one -->
                        <div class="row">
                            <div class="col-md-6">
                                {% if form.fee_frequency %}
                                    {{ form.fee_frequency|as_crispy_field }}
                                {% else %}
                                    <p class="text-danger">fee_frequency field not found</p>
                                {% endif %}
                            </div>
                            <div class="col-md-6">
                                {% if form.fiscal_year_end_month %}
                                    {{ form.fiscal_year_end_month|as_crispy_field }}
                                {% else %}
                                    <p class="text-danger">fiscal_year_end_month field not found</p>
                                {% endif %}
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                {% if form.investment_period_fee_basis %}
                                    {{ form.investment_period_fee_basis|as_crispy_field }}
                                {% else %}
                                    <p class="text-danger">investment_period_fee_basis field not found</p>
                                {% endif %}
                            </div>
                            <div class="col-md-6">
                                {% if form.divest_period_fee_basis %}
                                    {{ form.divest_period_fee_basis|as_crispy_field }}
                                {% else %}
                                    <p class="text-danger">divest_period_fee_basis field not found</p>
                                {% endif %}
                            </div>
                        </div>

                        {% if form.investment_period_end_date %}
                            {{ form.investment_period_end_date|as_crispy_field }}
                        {% else %}
                            <p class="text-danger">investment_period_end_date field not found</p>
                        {% endif %}

                        <!-- Temporarily comment out the custom period section -->
                        {% comment %}
                        <h6 class="mt-4 mb-3">Custom Period End Months</h6>
                        <p class="text-muted small">
                            Configure custom period end months for non-standard fee schedules.
                            Leave blank to use default periods based on frequency.
                        </p>

                        <div class="row">
                            {% for i in "1234" %}
                            <div class="col-md-3">
                                {% with field_name="period"|add:i|add:"_end_month" %}
                                    {% with field=form|get_field:field_name %}
                                        {% if field %}
                                            {{ field|as_crispy_field }}
                                        {% else %}
                                            <p class="text-danger small">Field {{ field_name }} not found</p>
                                        {% endif %}
                                    {% endwith %}
                                {% endwith %}
                            </div>
                            {% endfor %}
                        </div>
                        {% endcomment %}

                        <div class="mt-4">
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-save me-1"></i> {% if is_create %}Create{% else %}Save{% endif %} Parameters
                            </button>
                            <a href="{% url 'fund_parameter_list' %}" class="btn btn-outline-secondary">
                                Cancel
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="card">
                <div class="card-header">
                    <h6 class="card-title mb-0">Help & Guidance</h6>
                </div>
                <div class="card-body">
                    <h6>Fee Frequency</h6>
                    <p class="small text-muted">
                        How often management fees are calculated and charged.
                    </p>

                    <h6>Fee Basis</h6>
                    <p class="small text-muted">
                        <strong>Investment Period:</strong> {% if not is_create %}{{ object.get_investment_period_fee_basis_display }}{% else %}Based on committed capital during investment period{% endif %}<br>
                        <strong>Divestment Period:</strong> {% if not is_create %}{{ object.get_divest_period_fee_basis_display }}{% else %}Based on net invested capital after investment period{% endif %}
                    </p>

                    {% comment %}
                    <h6>Custom Periods</h6>
                    <p class="small text-muted">
                        Use for non-standard quarter ends (e.g., Jan, Apr, Jul, Oct).
                        Only the first 4 periods are used for quarterly frequency.
                    </p>
                    {% endcomment %}
                    
                    {% if is_create %}
                    <h6>Creating New Parameters</h6>
                    <p class="small text-muted">
                        Select a fund that doesn't already have parameters configured.
                        Each fund can only have one set of parameters.
                    </p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script>
// Show/hide custom period fields based on frequency
if (document.getElementById('id_fee_frequency')) {
    document.getElementById('id_fee_frequency').addEventListener('change', function() {
        const frequency = this.value;
        
        // Show/hide period fields
        for (let i = 1; i <= 4; i++) {
            const field = document.getElementById(`id_period${i}_end_month`);
            if (field) {
                const formGroup = field.closest('.form-group');
                
                if (frequency === 'M') { // Monthly - show all
                    formGroup.style.display = 'block';
                } else if (frequency === 'Q' && i <= 4) { // Quarterly - show 4
                    formGroup.style.display = 'block';
                } else if (frequency === 'S' && i <= 2) { // Semi-annual - show 2
                    formGroup.style.display = 'block';
                } else if (frequency === 'A' && i <= 1) { // Annual - show 1
                    formGroup.style.display = 'block';
                } else {
                    formGroup.style.display = 'none';
                }
            }
        }
    });

    // Trigger change on page load
    document.getElementById('id_fee_frequency').dispatchEvent(new Event('change'));
}
</script>
{% endblock %}

manager/templates/funds/fund_parameter_list.html
{% extends "base.html" %}
{% load custom_filters %}
{% load humanize %}

{% block content %}
<div class="container-fluid">
    <div class="row mb-4">
        <div class="col">
            <h2><i class="fas fa-cog me-2"></i>Fund Parameters</h2>
            <p class="text-muted">Configure management fee calculation settings for each fund</p>
        </div>
        <div class="col-auto">
            <!-- Add Create button here -->
            <a href="{% url 'fund_parameter_create' %}" class="btn btn-success me-2">
                <i class="fas fa-plus me-1"></i>Add Parameters
            </a>
            <a href="{% url 'calculate_management_fees' %}" class="btn btn-primary">
                <i class="fas fa-calculator me-1"></i>Calculate Fees
            </a>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Fund Name</th>
                            <th>Fee Frequency</th>
                            <th>Investment Basis</th>
                            <th>Divestment Basis</th>
                            <th>Fiscal Year End</th>
                            <th>Investment Period End</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for param in parameters %}
                        <tr>
                            <td>{{ param.fund.name }}</td>
                            <td>{{ param.get_fee_frequency_display }}</td>
                            <td>{{ param.get_investment_period_fee_basis_display }}</td>
                            <td>{{ param.get_divest_period_fee_basis_display }}</td>
                            <td>{{ param.get_fiscal_year_end_month_display }}</td>
                            <td>{{ param.investment_period_end_date }}</td>
                            <td>
                                <a href="{% url 'fund_parameter_edit' param.pk %}" class="btn btn-sm btn-outline-primary">
                                    <i class="fas fa-edit"></i> Edit
                                </a>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="7" class="text-center text-muted py-4">
                                <i class="fas fa-exclamation-circle me-2"></i>
                                No fund parameters configured. 
                                <a href="{% url 'fund_parameter_create' %}">Create fund parameters</a> to enable fee calculations.
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}